![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [8]:
my_array = np.arange(10)

my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:
my_array[-2:-4:-1]


array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [21]:
my_array[-8:-11:-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [28]:
matrix_4 = np.arange(1,21).reshape(4,5)
print(matrix_4)

matrix_4.T

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [30]:
matrix_4_copy = matrix_4[:2, :2].copy()
print(matrix_4_copy)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [32]:
matrix_4_copy_1 = matrix_4[:2, :3].copy()
print(matrix_4_copy_1)

[[1 2 3]
 [6 7 8]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [146]:
upper, lower = np.vsplit(matrix_4, [3])
print(upper[:3, ::-1])



[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [42]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [43]:

x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [54]:
x = np.arange(1, 21).reshape(2, 5, 2)

print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [59]:
array_10 = np.full(10, 0)
print(array_10.size)
print(array_10)

array_10[3] = 1
print(array_10)

10
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [63]:
array_11= np.arange(10,50)
array_11[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [65]:
array_12 = [1,2,0,0,4,0]

no_zero = np.nonzero(array_12)[0]
print(no_zero)

#Me saca los indices pero no los numeros.

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [74]:
array_13 = np.random.rand(10,10)

print("El maximo es", np.max(array_13))
print("El minimo es", np.min(array_13))

El maximo es 0.999261370310334
El minimo es 0.008924663481274853


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [77]:
array_13 = np.random.rand(30)

np.mean(array_13)

np.float64(0.485712733035358)

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [79]:
array_15 = np.ones((6, 6))
array_15[1:-1, 1:-1] = 0

print(array_15)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [90]:
array_16 = np.ones((8, 8))
array_16[::2, ::2] = 0     
array_16[1::2, 1::2] = 0  

print(array_16)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [93]:
array_17 = np.tile([[0, 1], [1, 0]], (4, 4))
print(array_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [104]:
array_18 = np.random.randint(50, size= (5,5))

mean = np.mean(array_18)
std= np.std(array_18)

normalizar = ((array_18 - mean) / std)
print(normalizar)

[[ 0.59090177 -0.9578327   1.00786874 -0.42173231  1.42483571]
 [-0.24303218  1.48440242  0.82916861 -0.83869928  1.60353584]
 [ 0.94830203 -0.9578327   1.48440242  0.05480137 -0.9578327 ]
 [-1.13653283  0.17393479 -0.65999915  1.54396913 -1.19609954]
 [-1.07696612 -0.3621656  -1.01739941 -1.19609954 -0.12389876]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [115]:
array_19 = np.arange(10)
array_19_1 = np.where((array_19 >= 3) & (array_19 <= 8), -1, array_19)
print(array_19_1)
array_19_2 = np.where((array_19 >= 3) & (array_19 <= 8), False, True)
print(array_19_2)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9]
[ True  True  True False False False False False False  True]
